#!/usr/bin/env perl

# Copyright (C) 2014 Rolando Pereira
#
# Author: Rolando Pereira <rolando_pereira@sapo.pt>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

use strict;
use warnings;



use Mojolicious::Lite;
use Mojolicious::Types;

use ParseGithubFeed;

app->secrets(['dummy passphrase since there are no logins in this site']);

# Documentation browser under "/perldoc"
plugin 'PODRenderer';

# get '/nomirror' => sub {
#   my $self = shift;

#   my $feed = ParseGithubFeed::getEmacsMirrors();

#   $self->render(text => $feed, format => 'xml');
# };

get '/' => sub {
  my $self = shift;

  my $feed = ParseGithubFeed::makeFeed();
  $self->render(text => $feed, format => 'xml');
};



app->start;


